#开发环境
#端口
server:
  port: 8081
#spring的配置
spring:
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lzy-his?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ENC(vZsl8gKuyFucS4eMJw+rDGA/k4TVUkQ84F4TdYKsWIbRiJhqxvgq7lW0Pi/y1mig)
    password: ENC(lFFAtOtPo7rfNAgQikYXdvdRwKkbsbvcCDsZLmquZQ6Xo0eFHnIqf3i5mRyjvKRz)
    #注入数据源的类型   默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #        login-username: root
        #        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true  #启用数据源监控
  #配置redis
  redis:
    port: 6380
    host: 120.76.195.46
    password: liu123456
    timeout: 20s
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#shiro配置
shiro:
  #login-url: /index.html
  anon-urls:
    - /login/doLogin*
    - /login/captcha*
    - /login/logout*
    #- /pay/callback*/**
    #    - /system/upload/*
    - /druid/**
  authc-urls:
    - /**
#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
##fastdfs的配置
#fdfs:
#  so-timeout: 2500       # 读取时间
#  connect-timeout: 600   # 连接超时时间
#  thumb-image:           # 缩略图
#    width: 100
#    height: 100
#  tracker-list:          # tracker服务配置地址列表
#    - 47.93.125.194:22122
#upload:
#  base-url: 47.93.125.194:8888
#  allow-types:
#    - image/jpeg
#    - image/png
#    - image/bmp
#dubbo配置
#dubbo:
#  application:
#    name: his-system-web-service
#  registry:
#    address: zookeeper://47.93.125.194:2181
#  consumer:
#    check: false
#  config-center:
#    timeout: 15
#文件服务器
#minio:
#  apiEndpoint: http://47.93.125.194:9000
#  #  proxyEndpoint: http://47.93.125.194:9000
#  accessKey: ENC(pjE0U3cHUCIzHmWUs0KzhTHvVLKTMh3t7gG4b+Z6mEyJTT39oOXk++RspdvqJM/A)
#  secretKey: ENC/SDDYhOq5AZJV3izK/3fnXErw1iidEzcImIQqn/QoiMmv6Y4LPTFOR3Ws+ZTvQ66)
jasypt:
  encryptor:
    password: liuzhaoyuan